### ISSUE TITLE
4. Functional: Search for deals

### ISSUE THREAD

**Issue by ChiragBellara7** [ChiragBellara7/567_ShoppingDealsTracker_API#13]
**Story**: As an API Developer, I want to implement endpoints for searching deals based on keywords or specific criteria to enable users to find relevant deals efficiently.

**Confirmation**: The user can search for deals by keywords or another specific criteria.

**Note**: The other criterias for the search can decided after further discussion and based on the availability of data and resources.

**Comment by ChiragBellara7** [comment]
Duplicate Requirement.

**Comment by sahib0177** [comment]
This search deal functionality will be implemented in Sprint3
