### ISSUE TITLE
Chase W. : Functional : #2.) Filter Specific Deals

### ISSUE THREAD

**Issue by Memotexe** [ChiragBellara7/567_ShoppingDealsTracker_API#2]
**Story:** As an API Developer, I want the ability to filter the deals based on certain values so that it can meet the consumers specifications.

**Confirmation:** Verify that the GET request returns deals matching the specified category in the response.

**Comment by ChiragBellara7** [comment]
#51  Added Methods to filter deals with price and category

**Comment by sahib0177** [comment]
Approved and Merged to Main Branch.

Thanks
Sahibeer
