### ISSUE TITLE
Harshitha : Functional Req 1 - : Retrieve List of Deals

### ISSUE THREAD

**Issue by harshitha-y** [ChiragBellara7/567_ShoppingDealsTracker_API#38]
As an API developer, I want to create an endpoint that allows clients to retrieve a list of available shopping deals.

Confirmation:

- Verify that the API endpoint returns a list of deals with accurate details.

- Ensure proper error handling for invalid requests or empty result sets.

**Comment by ChiragBellara7** [comment]
Duplicate Requirement.
