### ISSUE TITLE
Harshitha: Functional Req 3 - Popular deals

### ISSUE THREAD

**Issue by harshitha-y** [ChiragBellara7/567_ShoppingDealsTracker_API#40]
As an API developer, I want to be able to create endpoints to allow users to view the most popular deals on screen

Confirmation: 

- Confirm that the API accurately identifies and displays popular deals.
- Monitor and validate that the popularity ranking aligns with user engagement.

**Comment by ChiragBellara7** [comment]
Currently this is not a major requirement but if time permits we can implement this as a subset of sorting deals.
