### ISSUE TITLE
Harshitha: Functional Req 4 - Product description

### ISSUE THREAD

**Issue by harshitha-y** [ChiragBellara7/567_ShoppingDealsTracker_API#41]
As an API developer, I want to create endpoints for clients to fetch detailed information about a specific deal, including product details and expiration date.

Confirmation: 

- Verify that a valid request to the endpoint returns accurate and complete details for the specified deal.
- Confirm that the response includes the deal title, description, discount percentage, product details, expiration date and any other information present in the database.

**Comment by ChiragBellara7** [comment]
Duplicate Requirement.
