### ISSUE TITLE
Harshitha: Functional Req 5 - Filter Deals by Category

### ISSUE THREAD

**Issue by harshitha-y** [ChiragBellara7/567_ShoppingDealsTracker_API#42]
As an API developer, I want to implement an endpoint that allows clients to filter deals based on specific categories (e.g., electronics, fashion, price, etc).

Confirmation:

Confirm that the API endpoint filters deals correctly based on specified categories.

**Comment by ChiragBellara7** [comment]
Duplicate Requirement.
