### ISSUE TITLE
Chase W. : Functional : #5.) Keyword Search for Deals in the Database

### ISSUE THREAD

**Issue by Memotexe** [ChiragBellara7/567_ShoppingDealsTracker_API#5]
**Story:** As an API Developer, I want to be able to provide the ability to search for deals using keywords, so that the consumer can be specific in what type of deals they are looking for.

**Confirmation:** Create a GET request capable of returning deals containing the specified keywords a consumer entered in a response/form.

**Comment by sahib0177** [comment]
This user story is in scope of Sprint 3. Assigned to Harshitha

**Comment by sahib0177** [comment]
Backend endpoint implementation mostly completed! Now awaiting UI team's requirements for seamless integration. Sprint 4 goal: Gather UI request specifics for remaining components and integration. Development team to push code changes after receiving requirements from UI team
Thanks, 
Sahibeer.
