### ISSUE TITLE
Chase W. : Functional : #6.) Pull Unique Deals from the Database to be Displayed

### ISSUE THREAD

**Issue by Memotexe** [ChiragBellara7/567_ShoppingDealsTracker_API#6]
**Story:** As an API Developer, I want to retrieve detailed information about a specific deal using its unique ID so that it can be displayed to the consumer in a more detailed matter.

**Confirmation:** Ensure that a GET request to the database returns detailed information about the specified deal.

**Comment by harshitha-y** [comment]
Issue closed.
