### ISSUE TITLE
Chase W. : Non Functional: #2.) Scalability

### ISSUE THREAD

**Issue by Memotexe** [ChiragBellara7/567_ShoppingDealsTracker_API#8]
**Story:** As an API Developer, the system should be scalable to accommodate to any changes that the Product Owner requests, so that we can deal with adjustments without a loss/decrease in performance.

**Confirmation:** The System should be able to dynamically scale resources based on demand, with this the response times should remain consistent with little to no loss in performance.

**Comment by ChiragBellara7** [comment]
Duplicate Requirement
